insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,1,'广州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,2,'深圳市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,3,'珠海市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,4,'汕头市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,5,'韶关市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,6,'佛山市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,7,'江门市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,8,'湛江市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,9,'茂名市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,10,'肇庆市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,11,'惠州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,12,'梅州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,13,'汕尾市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,14,'河源市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,15,'阳江市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,16,'清远市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,17,'东莞市 ','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,18,'中山市 ','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,19,'潮州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,20,'揭阳市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,21,'云浮市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (2,22,'北京市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (3,23,'上海市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (4,24,'天津市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (5,25,'重庆市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,26,'杭州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,27,'宁波市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,28,'温州市 ','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,29,'嘉兴市 ','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,30,'湖州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,31,'绍兴市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,32,'金华市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,33,'衢州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,34,'舟山市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,35,'台州市 ','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,36,'丽水市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,37,'福州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,38,'厦门市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,39,'莆田市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,40,'三明市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,41,'泉州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,42,'漳州市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,43,'南平市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,44,'龙岩市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,45,'宁德市','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (33,46,'河内（直辖市）','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (34,47,'岘港（直辖市）','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (35,48,'海防（直辖市）','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (36,49,'芹苴（直辖市）','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (37,50,'胡志明市（直辖市）','zh_CN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,1,'TP Quảng Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,2,'TP Thẩm Quyến','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,3,'TP Châu Hải ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,4,'TP Sán Đầu','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,5,'TP Thiều Quan','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,6,'TP Phật Sơn','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,7,'TP Giang Môn','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,8,'TP Trạm Giang','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,9,'TP Mậu Danh ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,10,'TP Triệu Khánh ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,11,'TP Huệ Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,12,'TP Mai Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,13,'TP Sán Vĩ ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,14,'TP Hà Nguyên ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,15,'TP Dương Giang ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,16,'TP Thanh Viễn','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,17,'TP Đông Quản ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,18,'TP Trung Sơn ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,19,'TP Triều Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,20,'TP Yết Dương ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (1,21,'TP Vân Phù ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (2,22,'TP Bắc Kinh ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (3,23,'TP Thượng Hải ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (4,24,'TP Thiên Tân ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (5,25,'TP Trùng Khánh ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,26,'TP Hàng Châu','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,27,'TP Ninh Ba','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,28,'TP Ôn Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,29,'TP Gia Hưng','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,30,'TP Hồ Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,31,'TP Thiệu Hưng ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,32,'TP Kim Hoa ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,33,'TP Cù Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,34,'TP Châu Sơn ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,35,'TP Đài Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (6,36,'TP Lệ Thủy ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,37,'TP Phúc Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,38,'TP Hạ Môn','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,39,'TP Phủ Điền ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,40,'TP Tam Minh ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,41,'TP Tuyền Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,42,'TP Chương Châu ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,43,'TP Nam Bình ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,44,'TP Long Nham','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (7,45,'TP Ninh Đức ','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (33,46,'Hà Nội (thành phố trực thuộc trung ương)','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (34,47,'Đà Nẵng (thành phố trực thuộc trung ương)','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (35,48,'Hải Phòng (thành phố trực thuộc trung ương)','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (36,49,'Cần Thơ (thành phố trực thuộc trung ương)','vi_VN');
insert into ck_cities (`state_id`,`city_id`,`city`,`lang`) values (37,50,'TP Hồ Chí Minh (thành phố trực thuộc trung ương)','vi_VN');