insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,1,'越秀区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,2,'荔湾区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,3,'海珠区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,4,'天河区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,5,'白云区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,6,'黄埔区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,7,'番禺区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,8,'花都区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,9,'南沙区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,10,'萝岗区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,11,'增城市','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,12,'从化区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,13,'福田区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,14,'罗湖区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,15,'南山区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,16,'宝安区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,17,'龙岗区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,18,'盐田区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,19,'光明新区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,20,'高新区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (3,21,'香洲区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (3,22,'斗门区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (3,23,'金湾区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,24,'金平区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,25,'龙湖区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,26,'濠江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,27,'潮阳区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,28,'潮南区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,29,'澄海区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,30,'南澳县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,31,'浈江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,32,'武江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,33,'曲江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,34,'乐昌市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,35,'南雄市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,36,'始兴县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,37,'仁化县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,38,'翁源县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,39,'新丰县 ','zh_CN');

insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,40,'乳源瑶族自治县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,41,'禅城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,42,'南海区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,43,'顺德区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,44,'三水区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,45,'高明区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,46,'江海区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,47,'蓬江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,48,'新会区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,49,'台山市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,50,'开平市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,51,'鹤山市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,52,'恩平市','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,53,'赤坎区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,54,'霞山区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,55,'坡头区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,56,'麻章区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,57,'廉江市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,58,'雷州市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,59,'吴川市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,60,'遂溪县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,61,'徐闻县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,62,'茂南区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,63,'茂港区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,64,'高州市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,65,'化州市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,66,'信宜市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,67,'电白县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,68,'端州区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,69,'鼎湖区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,70,'高要市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,71,'四会市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,72,'广宁县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,73,'怀集县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,74,'封开县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,75,'德庆县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,76,'惠城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,77,'惠阳区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,78,'博罗县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,79,'惠东县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,80,'龙门县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,81,'梅江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,82,'兴宁市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,83,'梅 县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,84,'大埔县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,85,'丰顺县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,86,'五华县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,87,'平远县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,88,'蕉岭县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,89,'城 区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,90,'陆丰市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,91,'海丰县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,92,'陆河县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,93,'源城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,94,'紫金县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,95,'龙川县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,96,'连平县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,97,'和平县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,98,'东源县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,99,'江城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,100,'阳春市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,101,'阳西县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,102,'阳东县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,103,'清城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,104,'英德市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,105,'连州市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,106,'佛冈县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,107,'阳山县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,108,'清新县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,109,'连山壮族瑶族自治县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,110,'连南瑶族自治县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,111,'莞城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,112,'东城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,113,'南城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,114,'万江区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,115,'石岐区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,116,'东区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,117,'西区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,118,'南区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,119,'五桂山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (19,120,'湘桥区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (19,121,'潮安县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (19,122,'饶平县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,123,'榕城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,124,'普宁市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,125,'惠来县  ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,126,'揭东县  ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,127,'揭西县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,128,'云城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,129,'罗定市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,130,'新兴县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,131,'郁南县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,132,'云安县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,133,'东城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,134,'西城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,135,'朝阳区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,136,'海淀区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,137,'丰台区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,138,'石景山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,139,'房山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,140,'通州区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,141,'顺义区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,142,'大兴区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,143,'昌平区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,144,'平谷区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,145,'怀柔区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,146,'门头沟区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,147,'密云县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,148,'延庆县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,149,'黄浦区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,150,'普陀区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,151,'徐汇区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,152,'静安区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,153,'青浦区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,154,'卢湾区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,155,'长宁区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,156,'虹口区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,157,'闵行区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,158,'闸北区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,159,'杨浦区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,160,'嘉定区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,161,'宝山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,162,'松江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,163,'金山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,164,'浦东新区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,165,'崇明县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,166,'奉贤区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,167,'南汇区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,168,'和平区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,169,'河西区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,170,'河东区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,171,'红桥区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,172,'南开区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,173,'河北区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,174,'西青区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,175,'北辰区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,176,'津南区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,177,'东丽区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,178,'蓟县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,179,'宝坻区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,180,'静海县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,181,'宁河县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,182,'武清区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,183,'滨海新区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,184,'万州区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,185,'黔江区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,186,'涪陵区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,187,'渝中区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,188,'大渡口区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,189,'江北区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,190,'沙坪坝区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,191,'九龙坡区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,192,'南岸区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,193,'北碚区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,194,'渝北区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,195,'巴南区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,196,'长寿区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,197,'江津区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,198,'合川区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,199,'永川区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,200,'南川区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,201,'綦江区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,202,'大足区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,203,'铜梁区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,204,'璧山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,205,'潼南县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,206,'荣昌县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,207,'梁平县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,208,'城口县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,209,'丰都县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,210,'垫江县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,211,'武隆县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,212,'忠县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,213,'开县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,214,'云阳县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,215,'奉节县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,216,'巫山县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,217,'巫溪县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,218,'石柱土家族自治县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,219,'秀山土家族苗族自治县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,220,'酉阳土家族苗族自治县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,221,'彭水苗族土家族自治县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,222,'上城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,223,'下城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,224,'滨江区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,225,'拱墅区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,226,'西湖区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,227,'萧山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,228,'余杭区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,229,'江干区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,230,'建德市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,231,'富阳市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,232,'临安市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,233,'桐庐县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,234,'淳安县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,235,'江东区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,236,'海曙区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,237,'江北区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,238,'鄞州区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,239,'镇海区','zh_CN');

insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,240,'北仑区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,241,'余姚市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,242,'慈溪市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,243,'奉化市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,244,'象山县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,245,'宁海县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,246,'鹿城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,247,'瓯海区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,248,'龙湾区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,249,'瑞安市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,250,'乐清市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,251,'洞头县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,252,'永嘉县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,253,'平阳县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,254,'苍南县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,255,'文成县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,256,'泰顺县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,257,'南湖区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,258,'秀洲区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,259,'海宁市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,260,'平湖市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,261,'桐乡市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,262,'嘉善县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,263,'海盐县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,264,'吴兴区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,265,'南浔区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,266,'德清县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,267,'长兴县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,268,'安吉县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,269,'诸暨市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,270,'越城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,271,'上虞市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,272,'嵊州市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,273,'绍兴县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,274,'新昌县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,275,'婺城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,276,'金东区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,277,'义乌市','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,278,'东阳市','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,279,'兰溪市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,280,'永康市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,281,'武义县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,282,'浦江县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,283,'磐安县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,284,'柯城区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,285,'衢江区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,286,'江山市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,287,'常山县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,288,'开化县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,289,'龙游县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,290,'定海区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,291,'普陀区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,292,'岱山县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,293,'嵊泗县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,294,'椒江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,295,'黄岩区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,296,'路桥区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,297,'温岭市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,298,'临海市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,299,'玉环县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,300,'三门县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,301,'天台县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,302,'仙居县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,303,'莲都区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,304,'龙泉市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,305,'青田县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,306,'缙云县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,307,'遂昌县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,308,'松阳县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,309,'云和县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,310,'庆元县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,311,'景宁畲族自治县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,312,'鼓楼区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,313,'台江区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,314,'仓山区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,315,'马尾区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,316,'晋安区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,317,'福清市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,318,'长乐市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,319,'闽侯县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,320,'连江县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,321,'罗源县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,322,'闽清县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,323,'永泰县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,324,'平潭县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,325,'思明区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,326,'海沧区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,327,'湖里区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,328,'集美区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,329,'同安区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,330,'翔安区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,331,'城厢区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,332,'涵江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,333,'荔城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,334,'秀屿区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,335,'仙游县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,336,'梅列区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,337,'三元区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,338,'永安市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,339,'明溪县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,340,'清流县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,341,'宁化县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,342,'大田县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,343,'尤溪县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,344,'沙县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,345,'将乐县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,346,'泰宁县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,347,'建宁县','zh_CN');

insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,348,'鲤城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,349,'丰泽区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,350,'洛江区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,351,'泉港区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,352,'石狮市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,353,'晋江市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,354,'南安市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,355,'惠安县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,356,'安溪县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,357,'永春县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,358,'德化县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,359,'金门县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,360,'芗城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,361,'龙文区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,362,'龙海市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,363,'云霄县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,364,'漳浦县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,365,'诏安县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,366,'长泰县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,367,'东山县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,368,'南靖县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,369,'平和县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,370,'华安县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,371,'延平区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,372,'邵武市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,373,'武夷山市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,374,'建瓯市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,375,'建阳市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,376,'顺昌县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,377,'浦城县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,378,'光泽县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,379,'松溪县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,380,'政和县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,381,'新罗区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,382,'漳平市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,383,'长汀县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,384,'永定县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,385,'上杭县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,386,'武平县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,387,'连城县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,388,'蕉城区 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,389,'福安市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,390,'福鼎市 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,391,'霞浦县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,392,'古田县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,393,'屏南县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,394,'寿宁县 ','zh_CN');
	
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,395,'周宁县 ','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,396,'柘荣县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,397,'巴亭区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,398,'还剑区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,399,'栋多区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,400,'二征夫人区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,401,'青春区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,402,'西湖区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,403,'纸桥区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,404,'雄梅区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,405,'冷边区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,406,'海州区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,407,'清溪区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,408,'山茶区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,409,'五行山区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,410,'连照区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,411,'鸿鹂区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,412,'黎真区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,413,'吴权区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,414,'建安区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,415,'海安区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,416,'涂山市','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,417,'宁桥郡','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,418,'平水郡','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,419,'丐冷郡','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,420,'乌门郡','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,421,'丰田县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,422,'果多县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,423,'脱诺县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,424,'永盛县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,425,'新平区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,426,'富润区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,427,'平新区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,428,'新富区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,429,'首德区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,430,'平盛区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,431,'旧邑区','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,432,'芽皮县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,433,'庄鹏县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,434,'平政县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,435,'芹耶县','zh_CN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,1,'Khu Việt Tú ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,2,'Khu Lệ Loan ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,3,'Khu Hải Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,4,'Khu Thiên Hà ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,5,'Khu Bạch Vân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,6,'Khu Hoàng Phố ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,7,'Khu Phiên Ngung ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,8,'Khu Hoa Đô ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,9,'Khu Nam Cát ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,10,'Khu La Cương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,11,'TP Tăng Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (1,12,'Khu Thung Hóa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,13,'Khu Phúc Điền ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,14,'Khu La Hồ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,15,'Khu Nam Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,16,'Khu Bảo An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,17,'Khu Long Cương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,18,'Khu Diêm Điền ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,19,'Khu Quag Minh Mới ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (2,20,'Khu Cao Tân','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (3,21,'Khu Hương Châu','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (3,22,'Khu Đấu Môn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (3,23,'Khu Kim Loan ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,24,'Khu Kim Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,25,'Khu Long Hồ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,26,'Khu Hào Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,27,'Khu Triều Dương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,28,'Khu Triều Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,29,'Khu Trừng Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (4,30,'Khu Nam Áo','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,31,'Khu Trinh Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,32,'Khu Võ Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,33,'Khu Khúc Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,34,'Khu Lạc Xương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,35,'Khu Nam Hùng','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,36,'Khu Thủy Hưng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,37,' Khu Nhân Hóa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,38,'Khu Ông Nguyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,39,'Khu Tân Phong','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (5,40,'Huyện tự trị dân tộc Dao Nhũ Nguyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,41,'Khu Thiền Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,42,'Khu Nam Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,43,'Khu Thuận Đức ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,44,'Khu Tam Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (6,45,'Khu Cao Minh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,46,'Khu Giang Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,47,'Khu Bồng Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,48,'Khu Tân Hội ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,49,'Khu Đài Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,50,'Khu Khai Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,51,'Khu Hạc Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (7,52,'Khu Ân Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,53,'Khu Xích Khảm ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,54,'Khu Hà Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,55,'Khu Pha Đầu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,56,'Khu Ma Chương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,57,'TP Liêm Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,58,'TP Lôi Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,59,'TPNgô Xuyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,60,'Huyện Toại Khê','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (8,61,'Huyện Từ Văn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,62,'Khu Mậu Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,63,'Khu Mậu Cảng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,64,'TPCao Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,65,'TP Hóa Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,66,'TPTín Nghi ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (9,67,'Huyện Điện Bạch ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,68,'Khu Đoan Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,69,'Khu Đỉnh Hồ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,70,'TP Cao Yêu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,71,'TP Tứ Hội ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,72,'Huyện Quảng Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,73,'Huyện Hoài Tập ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,74,'Huyện Phong Khai ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (10,75,'Huyện Đức Khánh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,76,'Khu Huệ Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,77,'Khu Huệ Dương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,78,'Huyện Bác Lac ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,79,'Huyện Huệ Đông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (11,80,'Huyện Long Môn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,81,'Khu Mai Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,82,'Khu Hưng Ninh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,83,'Huyện Mai ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,84,'Huyện Đại Bộ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,85,'Huyện Phong Thuận ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,86,'Huyện Ngũ Hòa','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,87,'Huyện Bình Viễn','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (12,88,'Huyện Tiêu Lãnh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,89,'Thành Nội ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,90,'TP Lục Phong ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,91,'Huyện Hải Phong ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (13,92,'Huyện Lục Hà ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,93,'Khu Nguyên Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,94,'Huyện Tử Kim ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,95,'Huyên Long Xuyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,96,'Huyện Liên Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,97,'Huyện Hòa Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (14,98,'Huyêện Đông Nguyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,99,'Khu Giang Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,100,'TP Dương Xuân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,101,'Huyện Dương Tây ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (15,102,'Huyện DươngĐông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,103,'Khu Thanh Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,104,'TP Anh Đức ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,105,'TP Liên Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,106,'Huyện Phật Cương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,107,'Huyện Dương Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,108,'Huyện Thanh Tân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,109,'Huyện tự trị dân tộc Dao và dân tộc Choang Liên Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (16,110,'Huyện Tự Trị dân tộc Dao Liên Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,111,'Khu Quản Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,112,'Khu Đông Thành','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,113,'Khu Nam Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (17,114,'Khu Vạn Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,115,'Khu Thạch Kỳ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,116,'Khu Đông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,117,'Khu Tây ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,118,'Khu Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (18,119,'Khu Ngũ Quế Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (19,120,'Khu Tương Kiều ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (19,121,'Huyện Triều An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (19,122,'Huyện Nhiêu Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,123,'Khu Dung Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,124,'TP Phổ Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,125,'Huyện Huệ Lai ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,126,'Huyện Yết Đông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (20,127,'Huyện Yết Tây ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,128,'Khu Vân Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,129,'TP La Định ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,130,'Huyện Tân Hưng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,131,'Huyện Uất Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (21,132,'Huyện Vân An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,133,'Khu Đông Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,134,'Khu Tây Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,135,'Khu Triều Dương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,136,'Khu Hải Điện ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,137,'Khu Phong Đài ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,138,'Khu Thạch Cảnh Sơn','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,139,'Khu Phòng Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,140,'Khu Thông Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,141,'Khu Thuận Nghĩa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,142,'Khu Đại Hưng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,143,'Khu Xương Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,144,'Khu Bình Cốc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,145,'Khu Hoài Nhu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,146,'Khu Môn Đầu Câu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,147,'Huyện Mật Vân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (22,148,'Huyện Diên Khánh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,149,'Khu Hoàng Phố ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,150,'Khu Phổ Đà ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,151,'Khu Từ Hối ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,152,'Khu Tĩnh An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,153,'Khu Thanh Phố ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,154,'Khu Lô Loan ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,155,'Khu Trường Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,156,'Khu Hồng Khẩu','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,157,'Khu Mẫn Hàng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,158,'Khu Hạp Bắc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,159,'Khu Dương Phố ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,160,'Khu Gia Định ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,161,'Khu Bảo Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,162,'Khu Tùng Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,163,'Khu Kim Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,164,'Khu Phố Đông Mới','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,165,'Huyện Hùng Minh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,166,'Khu Phụng Hiền ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (23,167,'Khu Nam Hối ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,168,'Khu Hòa Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,169,'Khu Hà Tây ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,170,'Khu Hà Đông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,171,'Khu Hồng Kiều ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,172,'Khu Nam Khai ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,173,'Khu Hà Bắc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,174,'Khu Tây Thanh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,175,'Khu Bắc Thần ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,176,'Khu Tân Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,177,'Khu Đông Li ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,178,'Huyện Kế ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,179,'Khu Bảo Trì ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,180,'Huyện Tĩnh Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,181,'Huyện Ninh Hà ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,182,'Khu Võ Thanh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (24,183,'Khu Tân Hải Mới','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,184,'Khụ Vạn Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,185,'Khu Kiềm Giang','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,186,'Khu Bồi Lăng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,187,'Khu Du Trung ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,188,'Khu Đại Độ Khẩu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,189,'Khu Giang Bắc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,190,'Khu Cát Bình Đập ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,191,'Khu Cửu Long Pha ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,192,'Khu Nam Ngạn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,193,'Khu Bắc Bội ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,194,'Khu Du Bắc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,195,'Khu Ba Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,196,'Khu Trường Thọ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,197,'Khu Giang Tân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,198,'Khu Hợp Xuyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,199,'Khu Vĩnh Xuyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,200,'Khu Nam Xuyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,201,'Khu Kỳ Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,202,'Khu Đại Túc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,203,'Khu Đồng Lương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,204,'Khu Bích Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,205,'Huyện Đồng Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,206,'Huyện Vinh Xương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,207,'Huyện Lương Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,208,'Huyện Thành Khẩu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,209,'Huyện Phong Đô','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,210,'Huyện Điến Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,211,'Huyện Vũ Long ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,212,'Huyện Trung ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,213,'Huyện Khai ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,214,'Huyện Vân Dương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,215,'Huyện Phụng Tiết ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,216,'Huyện Vu Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,217,' Huyện Vu Khê','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,218,'Huyện Tự Trị dân tổ Thổ Gia Thạch Trụ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,219,'Huyện Tự Trị dân tổ Mèo và dân tổ Thổ Gia Tú Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,220,'Huyện Tự Trị dân tổ Mèo và dân tổ Thổ Gia Dậu Dương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (25,221,'Huyện Tự Trị dân tổ Mèo và dân tổ Thổ Gia Bành Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,222,'Khu Thượng Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,223,'Khu Hạ Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,224,'Khu Tân Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,225,'Khu Củng Thự ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,226,'Khu Tây Hồ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,227,'Khu Tiêu Sơn','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,228,'Khu Dư Hàng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,229,'Khu Giang Can ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,230,'TP Kiến Đức ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,231,'TP Phú Dương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,232,'TP Lâm An','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,233,'Huyện Đồng Lô','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (26,234,'Huyện Thuần An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,235,'Khu Giang Đông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,236,'Khu Hải Thự ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,237,'Khu Giang Bắc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,238,'Khu Ngân Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,239,'Khu Trấn Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,240,'Khu Bắc Luân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,241,'TP Dư Diêu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,242,'TP Từ Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,243,'TP Phụng Hóa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,244,'Huyện Tượng Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (27,245,'Huyện Ninh Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,246,'Khu Lộc Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,247,'Khu Âu Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,248,'Khu Long Loan ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,249,'TP Thụy An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,250,' TP Lạc Thanh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,251,'Huyện Động Đầu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,252,'Huyện Vĩnh Gia ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,253,'Huyện Bình Dương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,254,'Huyện Thương Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,255,'Huyện Văn Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (28,256,'Huyện Thái Thuận ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,257,'Khu Nam Hồ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,258,'Khu Tú Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,259,'TP Hải Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,260,'TP Bình Hồ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,261,'TP Đồng Hương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,262,'Huyện Gia Thiện ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (29,263,'Huyện Hải Diêm ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,264,'Khu Ngô Hưng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,265,'Khu Nam Tầm ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,266,'Huyện Đức Thanh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,267,'Huyện Trường Hưng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (30,268,'Huyện An Cát ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,269,'TP Chư Kỵ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,270,'Khu Việt Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,271,'TP Thượng Ngu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,272,'TP Thặng Châu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,273,'Huyện Thiệu Hưng ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (31,274,'Huyện Tân  Xương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,275,'Khu Vụ Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,276,'Khu Kim Đông ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,277,'TP Nghĩa Ô','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,278,'TP Đông Dương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,279,'TP Lan Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,280,'TP Vĩnh Khang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,281,'Huyện Vũ Nghĩa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,282,'Huyện Phố Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (32,283,'Huyện Bàn An','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,284,'Khu Kha Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,285,'Khu Cù Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,286,'TP Giang Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,287,'Huyện Thường Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,288,'Huyện Khai Hóa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (33,289,'Huyện Long Du ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,290,'Khu Định Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,291,'Khu Phổ Đà ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,292,'Huyện Đại Sơn  ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (34,293,'Huyện  Thặng Tứ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,294,'Khu Tiêu Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,295,'Khu Hoàng Nham ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,296,'Khu Lộ Kiều ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,297,'TP Ôn Lĩnh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,298,'TP Lâm Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,299,'Huyện Ngọc Hoàn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,300,'Huyện Tam Môn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,301,'Huyện Thiên Đài ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (35,302,'Huyện Tiên Cư','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,303,'Khu Liên Đô ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,304,'TP Long Tuyền ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,305,'Huyện Thanh Điền','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,306,'Huyện Tấn Vân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,307,'Huyện Toại Xương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,308,'Huyện Tùng Dương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,309,'Huyện Vân Hòa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,310,'Huyện Khánh Nguyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (36,311,'Huyện Tự Trị dân Tổ Xa Cảnh Ninh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,312,'Khu Cổ Lầu','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,313,'Khu Đài Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,314,'Khu Thương Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,315,'Khu Mã Vĩ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,316,'Khu Tấn An','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,317,'TP Phúc Thanh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,318,'TP Trường Lạc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,319,'Huyện Mân Hầu','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,320,'Huyện Liên Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,321,'Huyện La Nguyên','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,322,'Huyện Mân Thanh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,323,'Huyện Vĩnh Thái ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (37,324,'Huyện Bình Đàm ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,325,'Khu Tư Minh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,326,'Khu Hải Thương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,327,'Khu Hồ Lý','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,328,'Khu Tập Mỹ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,329,'Khu Đồng An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (38,330,'Khu Tường An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,331,'Khu Thành Sương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,332,'Khu Hàm Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,333,'Khu Lệ Thành','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,334,'Khu Tú Dữ ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (39,335,'Huyện Tiên Du  ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,336,'Khu Mai Liệt ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,337,'Khu Tam Nguyên ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,338,'TP Vĩnh An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,339,'Huyện Minh Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,340,'Huyện Thanh Lưu','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,341,'Huyện Ninh Hóa','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,342,'Huyện Đại Điền ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,343,'Huyện Vưu Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,344,'Huyện Cát','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,345,'Huyện Tương Lạc ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,346,'Huyện Thái Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (40,347,'Huyện Kiến Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,348,'Khu Lí Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,349,'Khu Phong Thạch','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,350,'Khu Lạc Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,351,'Khu Tuyền Cảng','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,352,'Khu Thạch Sư','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,353,'TP Tấn Giang ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,354,'TP Nam An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,355,'Huyện Huệ An','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,356,'Huyện An Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,357,'Huyện Vĩnh Xuân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,358,'Huyện Đức Hóa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (41,359,'Huyện Kim Môn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,360,'Khu  Hương Thành','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,361,'Khu Long Văn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,362,'TP Long Hải ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,363,'Huyện Vân Tiêu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,364,'Huyện Chương Phố ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,365,'Huyện Chiếu An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,366,'Huyện Trường Thái ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,367,'Huyện Đông Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,368,'Huyện Nam Tĩnh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,369,'Huyện Bình Hòa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (42,370,'Huyện Hòa An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,371,'Khu Yên Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,372,'TP Thiệu Vũ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,373,'TP Vũ Di Sơn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,374,'TP Kiến Âu ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,375,'TP Kiến Dương','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,376,'Huyện Thuận Xương ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,377,'Huyện Phố Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,378,'Huyện Quang Thạch ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,379,'Huyển Tùng Thủy ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (43,380,'Huyện Chính Hòa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,381,'Khu Tân La','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,382,'TP Chương Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,383,'Huyện Trường Thinh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,384,'Huyện Vĩnh Định ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,385,'Huyện Thượng Hàng','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,386,'Huyện Vũ Bình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (44,387,'Huyện Liên Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,388,'Khu Tiêu Thành ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,389,'TP Phúc An ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,390,'TP Phúc Đỉnh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,391,'Huyện Hà Phố ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,392,'Huyện Cổ Điền ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,393,'Huyện Bính Nam ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,394,'Huyện Thọ Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,395,'Huyện Chu Ninh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (45,396,'Huyện Chá Vinh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,397,'Quận Ba Đình ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,398,'Quận Hoàn Kiếm','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,399,' Quận Đống Đa ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,400,' Quận Hai Bà Trưng','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,401,'Quận Thanh Xuân ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,402,'Khu Hồ Tây','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,403,'Quận Cầu giấy','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,404,' Quận Hoàng Mai','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (46,405,' Quận Long Biên','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,406,'Quận Hải Châu','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,407,'Quận Thất Khê','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,408,' Quận Sơn Trà','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,409,'Quận Ngũ Hành Sơn','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (47,410,'Quận Liên Chiều','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,411,' Quận Hồng Bàng','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,412,'Quận Lê Chân','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,413,'Quận Ngô Quyền','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,414,'Quận Kiến An','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,415,'Huyện An Hải','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (48,416,' Thị xã Đồ Sơn','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,417,'Quận Ninh Kiều','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,418,'Quận Bình Thủy','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,419,'Quận Cái Răng','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,420,'Quận Ô Môn ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,421,'Huyện Phong Điền','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,422,'Huyện Cờ Đỏ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,423,'Huyện Thốt Nốt','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (49,424,'Huyện Vĩnh Thạnh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,425,' Quận Tân Bình','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,426,' Quận Phú Nhuận','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,427,' Quận Bình Tân','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,428,'Quận Tân Phú ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,429,'Quận Thủ Đức  ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,430,' Quận Bình Thạnh ','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,431,'Quận Gò Vấp','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,432,'Huyện Nhà Bè','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,433,'Huyện Hóc Môn','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,434,'Huyện Bình Chánh','vi_VN');
insert into ck_regions (`city_id`,`region_id`,`region`,`lang`) values (50,435,'Huyện Cần Giờ','vi_VN');