insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,1,'广东省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,2,'北京市','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,3,'上海市','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,4,'天津市','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,5,'重庆市','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,6,'浙江省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,7,'福建省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,8,'江苏省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,9,'山东省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,10,'湖南省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,11,'四川省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,12,'黑龙江省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,13,'辽宁省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,14,'吉林省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,15,'河北省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,16,'河南省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,17,'湖北省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,18,'山西省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,19,'陕西省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,20,'安徽省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,21,'海南省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,22,'云南省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,23,'甘肃省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,24,'贵州省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,25,'青海省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,26,'江西省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,27,'台湾省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,28,'内蒙古自治区','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,29,'广西壮族自治区','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,30,'宁夏回族自治区','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,31,'新疆维吾尔自治区','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,32,'西藏自治区','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,33,'河内（直辖市）','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,34,'岘港（直辖市）','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,35,'海防（直辖市）','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,36,'芹苴（直辖市）','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,37,'胡志明市（直辖市）','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,38,'和平省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,39,'山罗省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,40,'莱州省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,41,'奠边省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,42,'河江省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,43,'高平省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,44,'老街省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,45,'谅山省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,46,'宣光省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,47,'安沛省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,48,'太原省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,49,'富寿省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,50,'永富省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,51,'北江省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,52,'北宁省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,53,'广宁省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,54,'河西省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,55,'海阳省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,56,'兴安省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,57,'河南省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,58,'南定省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,59,'太平省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,60,'宁平省','zh_CN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,1,'tỉnh Quảng Đông ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,2,'tỉnh Bắc Kinh ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,3,'tỉnh Thượng Hải ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,4,'tỉnh Thiên Tân ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,5,'tỉnh Trùng Khánh ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,6,'tỉnh Chiết Giang','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,7,'tỉnh Phúc Kiến','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,8,'tỉnh Giang Tô','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,9,'tỉnh Sơn Đông','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,10,'tỉnh Hồ Nam ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,11,'tỉnh Tứ Xuyên ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,12,'tỉnh Hắc Long Giang','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,13,'tỉnh Liêu Ninh','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,14,'tỉnh Cát Lâm','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,15,'tỉnh Hà Bắc ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,16,'tỉnh Hà Nam','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,17,'tỉnh Hồ Bắc','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,18,'tỉnh Sơn Tây','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,19,'tỉnh Tiểm Tây','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,20,'tỉnh An Huy','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,21,'tỉnh Hải Nam ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,22,'tỉnh Vân Nam ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,23,'tỉnh Cam Túc ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,24,'tỉnh Qúy Châu ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,25,'tỉnh Thanh Hải ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,26,'tỉnh Giang Tây ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,27,'tỉnh Đài Loan ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,28,'Khu tự trị Nội Mông Cổ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,29,'Khu tự trị dân tộc Choang Quảng Tây','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,30,'Khu tự trị dân tộc Hồi Ninh Hà','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,31,'Khu tự trị dân tộc Duy Ngô Nhĩ Tân Cương ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (1,32,'Khụ Tự Trị Tây Tạng ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,33,'Hà Nội(thành phố trực thuộc trung ương)','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,34,'Dà Nẵng(thành phố trực thuộc trung ương)','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,35,'Hải phòng(thành phố trực thuộc trung ương)','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,36,'Cần Thơ(thành phố trực thuộc trung ương)','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,37,'TP Hồ Chí Minh(thành phố trực thuộc trung ương)','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,38,'tỉnh Hòa Bình','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,39,'tỉnh Sơn La','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,40,'tỉnh Lai Châu','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,41,'tỉnh Điện Biên ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,42,'tỉnh Hà Giang ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,43,'tỉnh Cao Bằng','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,44,'tỉnh Lao Cai ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,45,'tỉnh Lạng Sơn ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,46,'tỉnh Tuyên Quang ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,47,'tỉnh Yên Bái ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,48,'tỉnh Thái Nguyên ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,49,'tỉnh Phú Thọ ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,50,'tỉnh Vĩnh Phúc ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,51,'tỉnh Bắc Giang ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,52,'tỉnh Bắc Ninh','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,53,'tỉnh Quảng Ninh ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,54,'tỉnh Hà Tây ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,55,'tỉnh Hải Dương ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,56,'tỉnh Hững Yên ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,57,'tỉnh Hà Nam ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,58,'tỉnh Nam Định ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,59,'tỉnh Thaí Bình ','vi_VN');
insert into ck_states (`country_id`,`state_id`,`state`,`lang`) values (2,60,'tỉnh Ninh Bình ','vi_VN');